#---
#- name: Create Units directory
#  file: path="{{ playbook_dir }}/units state=directory"
#  tags:
#    - configuration
- name: Gather fleet machines info
  get_coreos_machines:
  register: fleetctl_hosts
  tags:
    - configuration
    - coreos_registry
- name: Find dns host
  choose_registry_machine: IPS="{{ item['IPS'] }}" IDS="{{ item['IDS'] }}"
  register: m_dns_host
  with_items:
    - "{{ fleetctl_hosts['stdout'] }}"
  tags:
    - configuration
    - coreos_registry
  notify:
    - Write DNS IP to coreos servers
    - Write DNS IP locally

# Create unit
- name: Create DNS Units
  template: src=skydns.service.j2 dest={{ playbook_dir }}/units/skydns.service
  tags:
    - configuration
- name: Submit DNS units
  shell: "fleetctl submit {{ playbook_dir }}/units/{{ item }}"
  with_items:
    - "skydns.service"
  tags:
    - fleet_submit
    - fleet_submit_registry
- name: Start DNS units
  shell: "fleetctl start {{ item }}"
  with_items:
    - "skydns.service"
  tags:
    - fleet_start
    - fleet_start_registry
