---
- name: Write DNS IP to coreos servers
  shell: fleetctl ssh {{ item }} "if [ \$(grep {{ dns_host }} /etc/hosts | wc -l) -gt 0 ]; then sudo sed -i 's/.*{{ dns_host }}.*/{{ m_dns_host.results[0].IP }} {{ dns_host }}/g' /etc/hosts; else echo \"{{ m_dns_host.results[0].IP }} {{ dns_host }}\" | sudo tee --append /etc/hosts 1>/dev/null ;fi"
  with_items: m_dns_host.results[0].item.IDS

- name: Write DNS IP locally
  shell: if [ $(grep {{ dns_host }} /etc/hosts | wc -l) -gt 0 ]; then sudo sed -i 's/.*{{ dns_host }}.*/{{ m_dns_host.results[0].IP }} {{ dns_host }}/g' /etc/hosts; else echo "{{ m_dns_host.results[0].IP }} {{ dns_host }}" | sudo tee --append /etc/hosts 1>/dev/null ;fi
